config/routes.rb
HeadingsProto::Application.routes.draw do
  get "main" => 'main#index'
  get "main/:category" => 'main#index'
  resources :headings

  root :to => 'main#index'

end

app/models/heading.rb
class Heading < ActiveRecord::Base
  attr_accessible :meta_title, :meta_description, :headings, :subtitle, :solid_color

  mount_uploader :image, FileUploader
  mount_uploader :mp4_video, FileUploader
  mount_uploader :webm_video, FileUploader

  # validate :file_size_validation

  private

  # def file_size_validation
  #   errors[:image] << "should be less than 5MB" if image.size > 5.megabytes
  #   errors[:mp4_video] << "should be less than 5MB" if mp4_video.size > 5.megabytes
  #   errors[:webm_video] << "should be less than 5MB" if webm_video.size > 5.megabytes
  # end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/headings_controller.rb
class HeadingsController < ApplicationController
    def index
        @headings = Heading.all
    end

    def show
        @heading = Heading.find(params[:id])
    end

    def new
        @heading = Heading.new
    end

    def edit
        @heading = Heading.find(params[:id])
    end

    def create
        puts "params: #{params}"

        @heading = Heading.new do |u|
            heading_params(u)
        end
        @heading.save!
        redirect_to headings_path
    end

    def update
        @heading = Heading.find(params[:id])
        @heading.tap do |u|
            heading_params(u)
        end

        if !@heading.save!
            render 'edit'
        end
        redirect_to headings_path
    end

    def destroy
        @heading = Heading.find(params[:id])
        @heading.destroy
        redirect_to headings_path
    end

private
    def heading_params(u)
        u.home_url = params[:home_url]
        u.meta_title = params[:meta_title]
        u.meta_description = params[:meta_description]
        u.heading = params[:heading]
        u.subtitle = params[:subtitle]
        u.solid_color = params[:solid_color]
        u.image = params[:image]
        u.remove_image = params[:remove_image] || nil
        u.mp4_video = params[:mp4_video]
        u.remove_mp4_video = params[:remove_mp4_video] || nil
        u.webm_video = params[:webm_video]
        u.remove_webm_video = params[:remove_webm_video] || nil

        # slab1
        u.slab1_color = params[:slab1_color]
        u.slab1_opacity = params[:slab1_opacity]
        u.slab1_txt_color = params[:slab1_txt_color]
        u.slab1_txt_opacity = params[:slab1_txt_opacity]
        u.slab1_txt_roll_color = params[:slab1_txt_roll_color]
        u.slab1_txt_roll_opacity = params[:slab1_txt_roll_opacity]
        u.slab1_txt_sel_color = params[:slab1_txt_sel_color]
        u.slab1_txt_sel_opacity = params[:slab1_txt_sel_opacity]

        # slab2
        u.slab2_color = params[:slab2_color]
        u.slab2_opacity = params[:slab2_opacity]
        u.slab2_txt_color = params[:slab2_txt_color]
        u.slab2_txt_opacity = params[:slab2_txt_opacity]
        u.slab2_txt_roll_color = params[:slab2_txt_roll_color]
        u.slab2_txt_roll_opacity = params[:slab2_txt_roll_opacity]
        u.slab2_txt_sel_color = params[:slab2_txt_sel_color]
        u.slab2_txt_sel_opacity = params[:slab2_txt_sel_opacity]
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @heading = Heading.find_by_home_url(request.original_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/headings_helper.rb
module HeadingsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/headings/_form_content.html.erb
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Home URL</label>
    <div class="col-sm-10">
        <input type="text" class="form-control form-control-sm" name="home_url" value="<%= @heading.home_url %>">
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</small>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Meta Title</label>
    <div class="col-sm-10">
        <input type="text" class="form-control form-control-sm" name="meta_title" value="<%= @heading.meta_title %>">
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Meta Description</label>
    <div class="col-sm-10">
        <input type="text" class="form-control form-control-sm" name="meta_description" value="<%= @heading.meta_description %>">
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Heading</label>
    <div class="col-sm-10">
        <textarea class="form-control" name="heading" rows="3"><%= @heading.heading %></textarea>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Subtitle</label>
    <div class="col-sm-10">
        <input type="text" class="form-control form-control-sm" name="subtitle" value="<%= @heading.subtitle %>">
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Background Color</label>
    <div class="col-sm-10">
        <input type="color" class="form-control form-control-sm" name="solid_color" value="<%= @heading.solid_color %>" style="width: 50px">
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Image</label>
    <div class="col-sm-10">
        <input type="file" class="form-control form-control-sm" name="image">
        <% if @heading.image.present? %>
            <img class="thumb" src="<%= @heading.image.url %>"/>
            <br/><input type="checkbox" name="remove_image"> Remove image<br>
        <% end %>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">MP4 Video</label>
    <div class="col-sm-10">
        <input type="file" class="form-control form-control-sm" name="mp4_video">
        <% if @heading.mp4_video.present? %>
            <video class="thumb" width="200" controls>
                <source src="https://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4">
                Your browser does not support HTML5 video.
            </video>
            <br/><input type="checkbox" name="remove_mp4_video"> Remove video<br>
        <% end %>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">WebM Video</label>
    <div class="col-sm-10">
        <input type="file" class="form-control form-control-sm" name="webm_video">
        <% if @heading.webm_video.present? %>
            <video class="thumb" width="200" controls>
                <source src="https://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4">
                Your browser does not support HTML5 video.
            </video>
            <br/><input type="checkbox" name="remove_webm_video"> Remove video<br>
        <% end %>
    </div>
</div>

<h4>Slab 1</h4>
<hr/>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Color</label>
    <div class="col-sm-1">
        <input type="color" class="form-control form-control-sm" name="slab1_color" value="<%= @heading.slab1_color %>" style="width: 50px">
    </div>
    <label class="col-sm-1 col-form-label col-form-label-sm">Opacity</label>
    <div class="col-sm-2">
        <input type="range" name="slab1_opacity" min="1" max="100" value="<%= @heading.slab1_opacity || '100' %>">
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Text Default</label>
    <div class="col-sm-1">
        <input type="color" class="form-control form-control-sm" name="slab1_txt_color" value="<%= @heading.slab1_txt_color %>" style="width: 50px">
    </div>
    <label class="col-sm-1 col-form-label col-form-label-sm">Opacity</label>
    <div class="col-sm-2">
        <input type="range" name="slab1_txt_opacity" min="1" max="100" value="<%= @heading.slab1_txt_opacity || '100' %>">
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Text Rollover</label>
    <div class="col-sm-1">
        <input type="color" class="form-control form-control-sm" name="slab1_txt_roll_color" value="<%= @heading.slab1_txt_roll_color %>" style="width: 50px">
    </div>
    <label class="col-sm-1 col-form-label col-form-label-sm">Opacity</label>
    <div class="col-sm-2">
        <input type="range" name="slab1_txt_roll_opacity" min="1" max="100" value="<%= @heading.slab1_txt_roll_opacity || '100' %>">
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Text Selected</label>
    <div class="col-sm-1">
        <input type="color" class="form-control form-control-sm" name="slab1_txt_sel_color" value="<%= @heading.slab1_txt_sel_color %>" style="width: 50px">
    </div>
    <label class="col-sm-1 col-form-label col-form-label-sm">Opacity</label>
    <div class="col-sm-2">
        <input type="range" name="slab1_txt_sel_opacity" min="1" max="100" value="<%= @heading.slab1_txt_sel_opacity || '100' %>">
    </div>
</div>

<h4>Slab 2</h4>
<hr/>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Color</label>
    <div class="col-sm-1">
        <input type="color" name="slab2_color" class="form-control form-control-sm" value="<%= @heading.slab2_color %>" style="width: 50px">
    </div>
    <label class="col-sm-1 col-form-label col-form-label-sm">Opacity</label>
    <div class="col-sm-2">
        <input type="range" name="slab2_opacity" min="1" max="100" value="<%= @heading.slab2_opacity || '100' %>">
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Text Default</label>
    <div class="col-sm-1">
        <input type="color" name="slab2_txt_color" class="form-control form-control-sm" value="<%= @heading.slab2_txt_color %>" style="width: 50px">
    </div>
    <label class="col-sm-1 col-form-label col-form-label-sm">Opacity</label>
    <div class="col-sm-2">
        <input type="range" name="slab2_txt_opacity" min="1" max="100" value="<%= @heading.slab2_txt_opacity || '100' %>">
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Text Rollover</label>
    <div class="col-sm-1">
        <input type="color" name="slab2_txt_roll_color" class="form-control form-control-sm" value="<%= @heading.slab2_txt_roll_color %>" style="width: 50px">
    </div>
    <label class="col-sm-1 col-form-label col-form-label-sm">Opacity</label>
    <div class="col-sm-2">
        <input type="range" name="slab2_txt_roll_opacity" min="1" max="100" value="<%= @heading.slab2_txt_roll_opacity || '100' %>">
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-sm">Text Selected</label>
    <div class="col-sm-1">
        <input type="color" name="slab2_txt_sel_color" class="form-control form-control-sm" value="<%= @heading.slab2_txt_sel_color %>" style="width: 50px">
    </div>
    <label class="col-sm-1 col-form-label col-form-label-sm">Opacity</label>
    <div class="col-sm-2">
        <input type="range" name="slab2_txt_sel_opacity" min="1" max="100" value="<%= @heading.slab2_txt_sel_opacity || '100' %>">
    </div>
</div>

app/views/headings/edit.html.erb
<div class="container">
  <br/>
  <p>
    <%= link_to "Back", headings_path, :class => "btn btn-primary" %>
  </p>
  <div class="panel panel-default">
    <div class="panel-heading">New Heading</div>
    <div class="panel-body">
      <%= form_tag '/headings/' +  @heading.id.to_s, :method => :put, :multipart => true do %>
        <%= render 'form_content' %>

        <div class="form-group row">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/headings/index.html.erb
<div class="container">
  <h2>Headings</h2>
  <p>
    <a href="/headings/new" class="btn btn-primary">New Heading</a>
    <a href="/main" class="btn btn-default">Back to Home</a>
  </p>
  <table class="table table-striped headings">
    <thead>
      <tr>
        <th>Id</th>
        <th>Meta Title</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @headings.each do |heading| %>
        <tr>
            <td><%= heading.id %></td>
            <td><%= heading.meta_title %></td>
            <td>
                <%= link_to 'Show', heading_path(heading), :class => "btn btn-primary btn-sm" %>
                <%= link_to 'Edit', edit_heading_path(heading), :class => "btn btn-primary btn-sm" %>
                <%= link_to 'Delete', heading_path(heading), 
                    method: :delete,
                    data: { confirm: 'Are you sure?' },
                    :class => "btn btn-primary btn-sm" %>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/headings/new.html.erb
<div class="container">
  <br/>
  <p>
    <%= link_to "Back", headings_path, :class => "btn btn-primary" %>
  </p>
  <div class="panel panel-default">
    <div class="panel-heading">New Heading</div>
    <div class="panel-body">
      <form action="/headings" method="post" enctype="multipart/form-data">
        
        <%= render 'form_content' %>
        
        <div class="form-group row">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Create</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/headings/show.html.erb
<div class="container">
  <br/>
  <p>
    <%= link_to "Back", headings_path, :class => "btn btn-primary" %>
  </p>
  <div class="panel panel-default">
    <div class="panel-heading">New Heading</div>
    <div class="panel-body">
      <form>
        
        <%= render 'form_content' %>
      </form>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>

  <!-- stylesheets -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
  <%= stylesheet_link_tag "application", :media => "all" %>

  <%= yield :head %>

  <!-- javascripts -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= javascript_include_tag "application" %>
</head>
<body>

  <%= yield %>

</body>
</html>

app/views/main/index.html.erb
<% content_for :head do %>
    <% if @heading %>
        <title><%= @heading.meta_title %></title>
        <meta name="description" content="<%= @heading.meta_description %>">
        <meta property="og:title" content="<%= @heading.meta_title %>">
        <meta property="og:description" content="<%= @heading.meta_description %>">
        <style>
                .slab1 {
                    background-color: <%= @heading.slab1_color %>;
                    opacity: <%= @heading.slab1_opacity / 100.0 %>;
                }

                .navbar-default .navbar-nav>li>a.slab1-text {
                    color: <%= @heading.slab1_txt_color %>;
                    opacity: <%= @heading.slab1_txt_opacity / 100.0 %>;
                }

                .slab2 {
                    background-color: <%= @heading.slab2_color %>;
                    opacity: <%= @heading.slab2_opacity / 100.0 %>;
                }

                .navbar-default .navbar-nav>li>a.slab2-text {
                    color: <%= @heading.slab2_txt_color %>;
                    opacity: <%= @heading.slab2_txt_opacity / 100.0 %>;
                }

                .heading {
                    background-color: <%= @heading.solid_color %>;
                    background-image: url("<%= @heading.image.url %>");
                }

                video {
                    position: absolute;
                    top: 0;
                    left: 0;
                    width: 100%;
                    object-fit: fill;
                }
        </style>
    <% end %>
<% end %>

<div class="container">
      <!-- Static navbar -->
    <nav class="navbar navbar-default slab1">
        <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/main">Placeit</a>
                </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/main/digital" class="slab1-text">Digital</a></li>
                    <li><a href="/main/apparel" class="slab1-text">Apparel + Print</a></li>
                    <li><a href="/main/design" class="slab1-text">Design</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/headings" class="slab1-text">Admin <span class="sr-only">(current)</span></a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
    </nav>

    <nav class="navbar navbar-default slab2">
        <div class="container-fluid">
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/main/digital" class="slab2-text">Digital</a></li>
                    <li><a href="/main/apparel" class="slab2-text">Apparel + Print</a></li>
                    <li><a href="/main/design" class="slab2-text">Design</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
    </nav>

    <!-- Main component for a primary marketing message or call to action -->
    <div class="jumbotron heading" style="position: relative">
        <% if @heading and !@heading.mp4_video.file.nil? %>
            <video width="320" height="260" controls>
                <source src="https://www.w3schools.com/html/movie.mp4" type="video/mp4"/>
            </video>
        <%end %>
        <h1>Header example</h1>
        <p>This example is a quick exercise to illustrate how the default, static navbar and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
    </div>

</div> <!-- /container -->